### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by TaiLinChung**
discord莊岱霖 first time in week04

testURL
http://34.201.179.190:3000/

I will try to use .env to improve the privacy tomorrow.
And I will code review with other classmate to learn more methon to finish the function tomorrow. 
Best wishes~~

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Password input should use input element with type password.
2. Sign out does not work properly. We should make sure API is completed before reloading page.

**Comment by TaiLinChung** [comment]
discord莊岱霖 second time in week04

testURL
http://34.201.179.190:3000/

Best wishes~~

**Comment by TaiLinChung** [comment]
discord莊岱霖 second time in week04

testURL
http://34.201.179.190:3000/

Best wishes~~

**Comment by cwpeng** [comment]
I cannot review for you.

**Comment by TaiLinChung** [comment]
discord莊岱霖 third time in week04

sorry for my fault ,i'v already reopen the request
testURL
http://34.201.179.190:3000/

Best wishes~~

**Comment by TaiLinChung** [comment]
> I cannot review for you.,
Sorry i'v already reopen the request,is it still something wrong?

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
